server:
  port: 8085
  
spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jeet0308/microservice-configuration
          clone-on-start: true
          